frontend/controllers/AccountController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Account;
use common\models\AccountSearch;
use common\models\AccountReport;
use common\models\AccountReportSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AccountController implements the CRUD actions for Account model.
 */
class AccountController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Account models.
     * @return mixed
     */
    public function actionIndex() {
        $searchDaily = new AccountReportSearch();
        $dataDaily = $searchDaily->search(Yii::$app->request->queryParams);
        $dataDaily->query->groupBy('date');
        
        $searchMonthly = new AccountReportSearch();
        $dataMonthly = $searchMonthly->search(Yii::$app->request->queryParams);
        $dataMonthly->query->groupBy('month');

        $searchYearly = new AccountReportSearch();
        $dataYearly = $searchYearly->search(Yii::$app->request->queryParams);
        $dataYearly->query->groupBy('year');

        $searchModel = new AccountSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->sort->defaultOrder = ['id' => SORT_DESC];
        $model = new Account();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session['date'] = $model->date;
            $model = new Account();
            return $this->redirect(['index']);
        }

        return $this->render('index', [
                    'model' => $model,
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'searchDaily' => $searchDaily,
                    'dataDaily' => $dataDaily,
                    'searchMonthly' => $searchMonthly,
                    'dataMonthly' => $dataMonthly,
                    'searchYearly' => $searchYearly,
                    'dataYearly' => $dataYearly,
        ]);
    }

    /**
     * Displays a single Account model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Account model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Account();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Account model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            // return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Account model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Account model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Account the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Account::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/controllers/OrdersController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Orders;
use common\models\Model;
use common\models\OrdersSearch;
use common\models\OrderItems;
use common\models\OrderItemsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrdersController implements the CRUD actions for Orders model.
 */
class OrdersController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Orders models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new OrderItemsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = new Orders();
        $modelItems = [new OrderItems()];

        if ($model->load(Yii::$app->request->post())) {
            $modelItems = \common\models\Model::createMultiple(OrderItems::classname());
            Model::loadMultiple($modelItems, Yii::$app->request->post());
            $valid = $model->validate();
            $valid = Model::validateMultiple($modelItems) && $valid;
            if ($valid) {
                $dbtransac = \Yii::$app->db->beginTransaction();
                try {
                    if (!$model->save()) {
                        Throw new Exception(' Detail transaksi tidak dapat disimpan.');
                    }
                    foreach ($modelItems as $modelItem) {
                        $modelItem->order_id = $model->id;
                        if (!$modelItem->save(false))
                            Throw new Exception(' Detail item pesanan tidak dapat disimpan.');
                    }
                    $dbtransac->commit();
                    $model = new Orders();
                    $modelItems = [new OrderItems()];
                    return $this->redirect(['index']);
                } catch (Exception $e) {
//                    \Yii::$app->notify->fail($e->getMessage());
                    $dbtransac->rollBack();
                } catch (\yii\db\Exception $e) {
                    \Yii::$app->notify->fail($e->getMessage());
                    $dbtransac->rollBack();
                }
            }
        }

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'model' => $model,
                    'modelItems' => $modelItems,
        ]);
    }

    /**
     * Displays a single Orders model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Orders model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Orders();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Orders model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Orders model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Orders model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Orders the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Orders::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <div class="wrap">

            <?php $this->beginBody() ?>
            <?php
            NavBar::begin([
                'brandLabel' => 'Rara Kitchy',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
//                    'class' => 'navbar-inverse navbar-static-top',
                ],
                'innerContainerOptions' => ['class' => 'container-fluid'],
            ]);
//            $bar = Html::tag('span', '', ['class' => 'icon-bar']);
//            $screenReader = "<span class=\"sr-only\">Toggle navigation</span>";
//            $menuItems1[] = Html::button("{$screenReader}<i class=\"fa fa-bars\" aria-hidden=\"true\"></i>", [
//                        'class' => 'sidebar-toggle',
//                        'role' => 'button',
//                        'data-toggle' => 'offcanvas',
//                        'data-target' => "#sidebar-left}",
//            ]);
//            echo Nav::widget([
//                'options' => ['class' => 'navbar-nav navbar-left'],
//                'items' => $menuItems1,
//            ]);
            $menuItemsLeft = [
                ['label' => 'Accounts', 'url' => ['/account/index']],
                ['label' => 'Stocks', 'url' => ['/raw-material/index']],
                ['label' => 'Clients', 'url' => ['/client/index']],
                ['label' => 'Orders', 'url' => ['/orders/index']],
                ['label' => 'Schedule', 'url' => ['/schedule/my-schedule']],
            ];
            $menuItems = [
                ['label' => 'Home', 'url' => ['/site/index']],
                ['label' => 'About', 'url' => ['/site/about']],
                ['label' => 'Contact', 'url' => ['/site/contact']],
            ];
            if (Yii::$app->user->isGuest) {
//                $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
                $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
            } else {
                $menuItems[] = '<li>'
                        . Html::beginForm(['/site/logout'], 'post')
                        . Html::submitButton(
                                'Logout (' . Yii::$app->user->identity->username . ')', ['class' => 'btn btn-link']
                        )
                        . Html::endForm()
                        . '</li>';
            }
            if (!Yii::$app->user->isGuest) {
                echo Nav::widget([
                    'options' => ['class' => 'navbar-nav navbar-left'],
                    'items' => $menuItemsLeft,
                ]);
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
            ?>

            <div class="container">
                <!--<div class="container-fluid">-->
                <?=
                Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ])
                ?>
                <?= Alert::widget() ?>

                <?= $content ?>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

                <p class="pull-right"><?= Yii::powered() ?></p>
            </div>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>